### PR TITLE
User guide for image annotation

### PR DESCRIPTION
**Pull request by FabianMauz**
Add a chapter for a user guide for the new image annotation feature. The chapter can be found at 

Chemotion ELN -> User Interface -> Image Edit/Annotation

### CODE REVIEW

**Comment by harivyasi** [comment]
@FabianMauz I will merge it later today so that you have the docs link in time for the meeting.

**Review by harivyasi — APPROVED** [review]

**Comment by FabianMauz** [comment]
Perfect, thank you.

Fabian Mauz
Softwareentwickler
Abt. Natur- und Wirkstoffchemie
Tel:
E-Mail:
+49 345 5582 1364
***@***.*** ***@***.***>
[https://mailtasticcdn.azureedge.net/img/images/siglinks/company/71639e11-6a7d-4a5d-bcf0-0b3dad2b4943/u_logo-TcV2hig3uu.png]
Leibniz-Institut für Pflanzenbiochemie
Weinberg 3 | 06120 Halle | Deutschland
Tel. +49 345 5582 0 | www.ipb-halle.de<http://www.ipb-halle.de/>
<https://app.mailtastic.de/api/linkserve/campaign/531c0b95-c246-4bf8-9b65-5eeaeab3e241/14999>

Von: Shashank S. Harivyasi ***@***.***
Gesendet: Dienstag, 7. März 2023 05:13
An: ComPlat/chemotion_saurus ***@***.***>
Cc: Mauz, Fabian ***@***.***>; Mention ***@***.***>
Betreff: Re: [ComPlat/chemotion_saurus] User guide for image annotation (PR #170)


@FabianMauz<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFabianMauz&data=05%7C01%7C%7Cfeea35842ef94b3ef16a08db1ec231bb%7C0934ee6c2a574efd80a9fc003defef4e%7C0%7C0%7C638137591668222178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MUhiArvaMNOUXkD7inTA6GQSHijohzQ6Ls2oTo2qAzU%3D&reserved=0> I will merge it later today so that you have the docs link in time for the meeting.

-

**Comment by harivyasi** [comment]
Here: https://www.chemotion.net/docs/eln/ui/images

**Comment by FabianMauz** [comment]
Thanks

Fabian Mauz
Softwareentwickler
Abt. Natur- und Wirkstoffchemie
Tel:
E-Mail:
+49 345 5582 1364
***@***.*** ***@***.***>
[https://mailtasticcdn.azureedge.net/img/images/siglinks/company/71639e11-6a7d-4a5d-bcf0-0b3dad2b4943/u_logo-TcV2hig3uu.png]
Leibniz-Institut für Pflanzenbiochemie
Weinberg 3 | 06120 Halle | Deutschland
Tel. +49 345 5582 0 | www.ipb-halle.de<http://www.ipb-halle.de/>
<https://app.mailtastic.de/api/linkserve/campaign/531c0b95-c246-4bf8-9b65-5eeaeab3e241/14999>

Von: Shashank S. Harivyasi ***@***.***
Gesendet: Dienstag, 7. März 2023 08:53
An: ComPlat/chemotion_saurus ***@***.***>
Cc: Mauz, Fabian ***@***.***>; Mention ***@***.***>
Betreff: Re: [ComPlat/chemotion_saurus] User guide for image annotation (PR #170)


Here: https://www.chemotion.net/docs/eln/ui/images<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.chemotion.net%2Fdocs%2Feln%2Fui%2Fimages&data=05%7C01%7C%7Cede5d7d7f349423f41d608db1ee0fcd8%7C0934ee6c2a574efd80a9fc003defef4e%7C0%7C0%7C638137723881611769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OEE%2B16NGMENLzu1kUZJuc7kBF5ZQ6SoQTegtfsdQjN4%3D&reserved=0>

-

**Pull request merged**
