### PR TITLE
Fix 155 respect user privacy

### PR DESCRIPTION
**Pull request by harivyasi**

### CODE REVIEW

**Comment by harivyasi** [comment]
@PiTrem It now works as intended. Three examples are attached.

image

image

image

**Comment by harivyasi** [comment]
Additional big thanks to @jliermann for developing the plugin. :)

**Comment by jliermann** [comment]
You are welcome!

We are using this (more specific) text on our [knowledge base](https://raw.githubusercontent.com/NFDI4Chem/knowledge_base/main/docs/40_smartlab/20_chemotion_eln.mdx):
```YouTube uses cookies and stores personal data. To view embedded videos from YouTube, please indicate your consent to load this video from anexternal source.```

**Review by PiTrem — APPROVED** [review]
LG2M

**Pull request merged**
