### PR TITLE
introduces local search

### PR DESCRIPTION
**Pull request by harivyasi**
- introduces localized search that builds index on build
- removes Algolia connection
- reduces dependencies by replacing `presets` with selected `plugins` (see [here](https://github.com/ComPlat/chemotion_saurus/security/dependabot))

### CODE REVIEW

**Review by JanCBrammer — COMMENTED** [review]
I have mixed feelings about this.
Pro:
- Getting rid of Algolia means we don't need the accounts anymore. I didn't like that the accounts put the maintenance on those who had an account (and happened to not forget their credentials :laughing: ). In other words, I like that the search is "closer to the code" and hence more accessible.

Con:
- What about performance / how responsive is the local search?
- We're trading off not having to configure search externally anymore against having to maintain the search code under `src/theme/SearchBar`. Not sure what's the lesser of those two evils :upside_down_face: Is that code auto-generated or written by hand?
- How much do we want to rely on https://github.com/praveenn77/docusaurus-lunr-search being around for the long run vs. Algolia?

**Comment by harivyasi** [comment]
I have mixed feelings as well, along exactly the points that you raised:

Pros:
- No linking to Algolia also makes it more in line with GDPR -- we do not send anything to third-party providers.
- Since everything is statically build, including search, we can use this in future _to include the docs inside the distribution_. This will permanently solve the problem of versioned docs (people will always have docs relevant to their version).

Cons:
- In my local build, there was no difference in responsiveness. (I can spend some time getting the numbers if you are interested).
- The code was auto generated. For future reference, I ran `docusaurus swizzle docusaurus-lunr-search SearchBar --eject --danger` to generate it. 
- Local search is not officially supported but there are a [few community options to choose from](https://docusaurus.io/community/resources#search).

To add, local search (and docusaurus) is also used by [NFDI KB](https://knowledgebase.nfdi4chem.de/knowledge_base/) so we can also ask them about their experience.

**Comment by JanCBrammer** [comment]
The fact that the code under `src/theme/SearchBar` is auto-generated, takes away my biggest concern that we'd need to maintain a hand-crafted search.

Also, the local search on https://knowledgebase.nfdi4chem.de/knowledge_base/ seems super responsive. However, they seem to be using a different search package: https://github.com/NFDI4Chem/knowledge_base/blob/e17b96b49c071c5db9b0b8a34ddd7ce9cbbc8206/package.json#L19.

I couldn't get the search to work locally when serving the site from my devcontainer, but looking at the [docs](https://github.com/praveenn77/docusaurus-lunr-search/blob/c476634e63e841075aef144225976b0edce4018f/README.md) it seems that local development isn't supported yet.

**Comment by harivyasi** [comment]
Yes, local dev is not supported. I had to `npm run build` and `npm run serve` to test it.
(Please note that you will need to install the supporting packages first using `npm install`).

I know that NFDI KB are using a different package; I just picked what seemed easy, while following the order of this [list](https://docusaurus.io/community/resources#search). As far as I could tell, they are essentially the same.

**Comment by harivyasi** [comment]
Deprecated in favor of PR #164

**Pull request closed without merging**
