### PR TITLE
Remove versioning document

### PR DESCRIPTION
**Pull request by Allenskywalker92**

### CODE REVIEW

**Review by JanCBrammer — CHANGES_REQUESTED** [review]
Could you make sure that sidebars.js` is up to date with `versioned_sidebars/version-1.1.1-sidebars.json` (i.e., the latest version)? As far as I can tell this is currently not the case. Also, could you make sure that the directory structure corresponds to version 1.1.1? Currently, this is not the case. For example there's a `docs/eln/development/development.mdx` in the current version, which has been removed in 1.1.1.

**Comment by Allenskywalker92** [comment]
@JanCBrammer I updated it. Please check it again.

**Review by JanCBrammer — CHANGES_REQUESTED** [review]
Could you make sure that there's no diff when running the following command?

`git diff master -- versioned_docs/version-1.1.1/ remove-versioning -- docs/`

These two folders should have the same content, i.e., there shouldn't be a diff.
When I run the above git command, I get a diff.

**Comment by Allenskywalker92** [comment]
> Could you make sure that there's no diff when running the following command?
> 
> `git diff master -- versioned_docs/version-1.1.1/ remove-versioning -- docs/`
> 
> These two folders should have the same content, i.e., there shouldn't be a diff. When I run the above git command, I get a diff.

Is it the correct command? Looks like it is comparing the master docs folder with my branch 
image

**Comment by JanCBrammer** [comment]
I have the latest changes from your `remove-versioning` branch checked out locally .
Running `git diff remove-versioning -- docs/ origin/master -- versioned_docs/version-1.1.1/` gives me no diff. 
To make sure the git command is informative/correct, I locally made a change "x" to a file in `docs/` of `remove-versioning` and run the git command again. I then get a diff that only shows the change "x". That's good news because it indicates that  `docs/` on `remove-versioning` is now identical with the `versioned_docs/version-1.1.1/` on `master`.

For reference (for my future self):
`git diff A B` show  the list of changes that A would bring in if you merged it into B. That's not the same as all differences between A and B. That's why `git diff A B` gives a different result than `git diff B A`.

**Review by JanCBrammer — APPROVED** [review]

**Pull request merged**
